/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "GPIO.h"
#include "SPI.h"
#include "stm32f446zxx.h"
#include "stm32f446zxx_nvic.h"
#include <stdint.h>

#include <stdint.h>
// Include your custom device header here, e.g., #include "stm32f4xx.h"

void SPIinit(SPI_config_t *pSPIx)
{
}

void SPI1_IRQHandler(SPI_Handler *pSPIx)
{
}

int main(void)
{
    // GPIO_Handle_t spiPin;
    // SPI_Handler master;

    // spiPin.GPIOx = GPIOB;
    // spiPin.pinConfig.GPIO_PinMode = GPIO_MODE_AF;
    // spiPin.pinConfig.GPIO_PinOPType = GPIO_OTYPE_PP;
    // spiPin.pinConfig.GPIO_PinPuPd_control = GPIO_PULL_NONE;
    // spiPin.pinConfig.GPIO_PinSpeed = GPIO_SPEED_HIGH;
    // spiPin.pinConfig.GPIO_AltFuncMode = 5;

    // GPIO_ClockControl(GPIOB, ENABLE); // Turn on clock first!
  

    // spiPin.pinConfig.GPIO_PinNumber = PIN_13; // SCLK
    // GPIO_init(&spiPin);

    // spiPin.pinConfig.GPIO_PinNumber = PIN_15; // MOSI
    // GPIO_init(&spiPin);

    // spiPin.pinConfig.GPIO_PinNumber = PIN_14; // MISO
    // GPIO_init(&spiPin);

    // spiPin.pinConfig.GPIO_PinNumber = PIN_12; // NSS
    // GPIO_init(&spiPin);
    

    // master.pConfig.SPI_DeviceMode = MASTER;
    // master.pConfig.SPI_BusConfig = FULL_DUPLEX;
    // master.pConfig.CPHA = CPOL_IDLE_LOW;
    // master.pConfig.CPOL = CPHA_FIRST_EDGE;
    // master.pConfig.SSM = SSM_EN;
    // master.pConfig.Speed = FCLK_8;
    // master.pConfig.SPI_DFF = DFF_8B;
    // master.pSPIx = SPI1;

    // SPI_init(&master);
    // SPI_ClockControl(&master, ENABLE);

    // char buffer[] = "Hello";
    // int size = sizeof(buffer) / sizeof(buffer[0]);

    // // SPI_Send(&master, (uint8_t*)buffer, size);

    // NVIC_IRQ_PrioConfig(IRQ_NO_SPI1, 2);
    // NVIC_IRQConfig(IRQ_NO_SPI1, ENABLE);

    // SPI_SendDataIT(&master, (uint8_t *)buffer, size);

    // // SPI_ReceiveDataIT(&master, (uint8_t*)buffer, size);

    // /* Loop forever */
    // for (;;)
    // {
    //     // Application code goes here
    // }

    return 0;


    //Hoiiiiiiiiiiiiiii
}
